site_name: Progettazione di software interattivi
site_url: https://mydomain.org/mysite
theme:
  name: material
  icon:
   logo: fontawesome/solid/a 
  palette:
   - scheme: default 
     primary: blue
     toggle: 
       icon: material/weather-night
       name: Scuro     
   - scheme: slate 
     primary: black
     accent: orange
     toggle: 
       icon: material/weather-sunny
       name: Chiaro   

  features:
    - navigation.instant 
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky     
    - navigation.instant.preview
    - navigation.tracking
    - navigation.sections
    - toc.integrate
    - navigation.expand

nav:
  - Home: index.md
  - Progetto:
    - Titoloprogetto: project1/project.md
      
  - Documentazione:
    - Sperimentazioni: Documentazione/Progetto.md

  - Biografia:
    - Studi: Biografia/Biografia.md  

  - Altri progetti:
    - Reportage: Altriprogetti/Reportage.md

markdown_extensions:
  - attr_list
  - md_in_html
  
site_name: Progettazione di software interattivi
site_url: https://mydomain.org/mysite
theme:
  name: material
  icon:
   logo: fontawesome/solid/a 
  palette:
   - scheme: default 
     primary: blue
     toggle: 
       icon: material/weather-night
       name: Scuro     
   - scheme: slate 
     primary: black
     accent: orange
     toggle: 
       icon: material/weather-sunny
       name: Chiaro   

  features:
    - navigation.instant 
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky     
    - navigation.instant.preview

nav:
  - Home: index.md

  - Documentazione:
    - Graffiti: PiazzaGaribaldi/Progetto.md

  - Biografia:
    - Studi: Biografia/Biografia.md  

  - Altri progetti:
    - Reportage: Altriprogetti/Reportage.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption    